kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: expense
spec:
  selector:
    name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP