kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: expense
spec:
  selector:
    name: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30413
  type: LoadBalancer