apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-practice-cluster
  region: us-east-1

nodeGroups:
  - name: expense
    instanceType: "t3.small"
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    instancesDistribution:
      maxPrice: "0.04"
      instanceTypes: ["t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "lowest-price"
    labels: { role: worker }
    tags:
      nodegroup-role: worker
